# Generated by Django 5.2.4 on 2025-09-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muayclass1',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
