# Generated by Django 4.2.25 on 2025-10-31 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MuayClass1',
            new_name='MuayClass',
        ),
    ]
