# Generated by Django 4.2.25 on 2025-11-02 01:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0002_rename_muayclass1_muayclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='registration',
            name='muay_class',
            field=models.ManyToManyField(related_name='classes', to='schedule.muayclass'),
        ),
        migrations.AddField(
            model_name='registration',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
