# Generated by Django 4.2.25 on 2025-10-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_muayclass1_title_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
