# Generated by Django 4.2.25 on 2025-11-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('schedule', '0004_remove_registration_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MuayClass',
        ),
        migrations.AlterField(
            model_name='registration',
            name='muay_class',
            field=models.ManyToManyField(related_name='registrations', to='classes.muayclass'),
        ),
    ]
