# Generated by Django 4.2.25 on 2025-10-13 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_reviews_user_reviews_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
