# Generated by Django 4.2.25 on 2025-11-25 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_delete_muayclass_alter_registration_muay_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
