# Generated by Django 4.2.25 on 2025-11-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
