# Generated by Django 4.2.25 on 2025-11-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_delete_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
